import sys
import os

Import ( 'boost_options' )
Import ( 'getCurrentPath' )
Import(  'masterEnv','setupIncludeInstallAll' )

# add heavily modified boost bindings to include paths
boost_options[ 'CPPPATH' ] = boost_options.get( 'CPPPATH', [] ) + [ getCurrentPath() ]

env = masterEnv.Clone()
setupIncludeInstallAll(env, '.')
setupIncludeInstallAll(env, '.', '.hpp')

Export ( 'boost_options' )


